package com.maple.selenium.friefox;

import java.util.HashMap;
import java.util.Map;

import org.junit.After;
import org.junit.Before;
// Generated by Selenium IDE
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.firefox.FirefoxOptions;

/**
 * 
 * @Description: geckodriver-v0.21.0 , Firefox 57 , Selenium -3.141.59
 * @author: uwank171 
 * @date: 2020年10月29日 下午2:06:39 
 *
 */
public class FirefoxDemo001_57 {
	private WebDriver driver;
	private Map<String, Object> vars;
	JavascriptExecutor js;

	@Before
	public void setUp() {
		System.out.println("========= 开始  ==========");
		String firefox_path = "C:\\2020yanfeng\\Program Files\\Mozilla Firefox57\\firefox.exe";
		String firefox_driver_path = ".\\src\\main\\resources\\driver\\firefox_0_21_0\\geckodriver.exe";
		// 火狐的安装位置
		System.setProperty("webdriver.firefox.bin", firefox_path);
		// 加载驱动 webdriver.gecko.driver --> 47以上版本使用
		System.setProperty("webdriver.gecko.driver", firefox_driver_path);
		
		// 无界面启动（不启动浏览器）
		FirefoxOptions options = new FirefoxOptions();
		options.setHeadless(true);
		driver = new FirefoxDriver(options);
		
//		driver = new FirefoxDriver();
		js = (JavascriptExecutor) driver;
		vars = new HashMap<String, Object>();

	}

	@After
	public void tearDown() throws Exception {
		Thread.sleep(2000);
		System.out.println("========= 关闭 ============");
		driver.quit();
	}

	@Test
	public void demo001() {
		try {
			long l = System.currentTimeMillis();
			driver.get("http://www.baidu.com");
			driver.findElement(By.id("kw")).sendKeys("王魁");
			driver.findElement(By.id("su")).click();
			Thread.sleep(1000);
			driver.findElement(By.cssSelector("#\\31  > h3:nth-child(1) > a:nth-child(1)")).click();
			System.out.println("==耗时：" + (System.currentTimeMillis() - l - 1000) + " 毫秒");

		} catch (Exception e) {
			System.err.println("\n==== " + e);
		}

	}

}
