package com.maple.selenium.chrome;

import java.util.HashMap;
import java.util.Map;

import org.junit.After;
import org.junit.Before;
// Generated by Selenium IDE
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;

/**
 * 
 * @Description: chromedriver-80.0.3987.16 , Firefox-80.0.3987.132(64位) , Selenium-3.141.59
 * @author: uwank171 
 * @date: 2020年10月29日 下午2:07:25 
 *
 */
public class ChromeDemo001_80 {
	private WebDriver driver;
	private Map<String, Object> vars;
	JavascriptExecutor js;

	@Before
	public void setUp() {
		System.out.println("========= 开始  ==========");
		String chrome_driver_path = ".\\src\\main\\resources\\driver\\chrome_80_0_3987_16\\chromedriver.exe";

		System.setProperty("webdriver.chrome.driver", chrome_driver_path);
		// 无界面启动（不启动浏览器）
		ChromeOptions options = new ChromeOptions();
		options.setHeadless(true);
		driver = new ChromeDriver(options);
		
//		driver = new ChromeDriver();
		js = (JavascriptExecutor) driver;
		vars = new HashMap<String, Object>();

	}

	@After
	public void tearDown() throws Exception {
		Thread.sleep(2000);
		System.out.println("========= 关闭 ============");
		driver.quit();
	}

	@Test
	public void demo001() {
		try {
			long l = System.currentTimeMillis();
			driver.get("http://www.baidu.com");
			driver.findElement(By.id("kw")).sendKeys("王魁");
			driver.findElement(By.id("su")).click();
			Thread.sleep(1000);
			driver.findElement(By.cssSelector("#\\31  > h3:nth-child(1) > a:nth-child(1)")).click();
			System.out.println("==耗时：" + (System.currentTimeMillis() - l - 1000) + " 毫秒");

		} catch (Exception e) {
			System.err.println("\n==== " + e);
		}

	}

}
